version: '3.8'

services:
  frontend:
    container_name: react-frontend
    build:
      context: .
      dockerfile: front-side/webappts/Dockerfile
    ports:
      - "3000:80"
    depends_on:
      - backend

  backend:
    container_name: spring-backend
    build:
      context: .
      dockerfile: back-side/persistence/Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - database

  database:
    container_name: mysql-db
    image: mysql:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD:
      MYSQL_DATABASE: hospital_management
      MYSQL_USER: access
      MYSQL_PASSWORD: passer2023
    ports:
      - "3306:3306"
