version: '3.8'

services:
  springboot-app:
    container_name: spring
    build:
      context: .
      dockerfile: Dockerfile.spring
    ports:
      - "9090:80"
    environment:
      MYSQL_HOST: mysqldb
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      MYSQL_PORT: 3306
  mysqldb:
    container_name: mysqldb
    image: mysql
    volumes:
      - /home/neo/Desktop/db:/var/lib/mysql
    ports:
      - 3307:3306
    environment:
      MYSQL_DATABASE: hospital_management
      MYSQL_ROOT_PASSWORD: root


  frontend:
    container_name: react-frontend
    build:
      context: .
      dockerfile: Dockerfile.react
    ports:
      - "9090:80"
